services:
    postgres:
        image: postgres
        container_name: postgres-db
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: teacher_reviews
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    
    app:
        build: .
        container_name: teacher-reviews-app
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/teacher_reviews
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: password
        depends_on:
            - postgres

volumes:
    postgres_data: